name: Update assets

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions: {}

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v6

      - name: Generate stats card
        uses: readme-tools/github-readme-stats-action@v1.1.0
        with:
          card: stats
          options: username=${{ github.repository_owner }}&show_icons=true&theme=transparent
          path: assets/stats.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate top languages card
        uses: readme-tools/github-readme-stats-action@v1.1.0
        with:
          card: top-langs
          options: username=${{ github.repository_owner }}&layout=compact&langs_count=5&theme=transparent
          path: assets/langs.svg
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Generate pin card (WixiBot)
        uses: readme-tools/github-readme-stats-action@v1.1.0
        with:
          card: pin
          options: username=${{ github.repository_owner }}&repo=WixiBot&theme=transparent
          path: assets/repos/WixiBot.svg
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Generate pin card (Server)
        uses: readme-tools/github-readme-stats-action@v1.1.0
        with:
          card: pin
          options: username=${{ github.repository_owner }}&repo=Server&theme=transparent
          path: assets/repos/Server.svg
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Generate pin card (Website)
        uses: readme-tools/github-readme-stats-action@v1.1.0
        with:
          card: pin
          options: username=${{ github.repository_owner }}&repo=Website&theme=transparent
          path: assets/repos/Website.svg
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Generate pin card (YouTube Alt)
        uses: readme-tools/github-readme-stats-action@v1.1.0
        with:
          card: pin
          options: username=${{ github.repository_owner }}&repo=YouTube-Alt&theme=transparent
          path: assets/repos/YouTube-Alt.svg
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Generate pin card (TIPE)
        uses: readme-tools/github-readme-stats-action@v1.1.0
        with:
          card: pin
          options: username=${{ github.repository_owner }}&repo=TIPE&theme=transparent
          path: assets/repos/TIPE.svg
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Generate pin card (Atoll)
        uses: readme-tools/github-readme-stats-action@v1.1.0
        with:
          card: pin
          options: username=Ebullioscopic&repo=Atoll&theme=transparent
          path: assets/repos/Atoll.svg
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Generate pin card (12-th Client)
        uses: readme-tools/github-readme-stats-action@v1.1.0
        with:
          card: pin
          options: username=${{ github.repository_owner }}&repo=12th-Client&theme=transparent
          path: assets/repos/12th-Client.svg
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Generate WakaTime card
        uses: readme-tools/github-readme-stats-action@v1.1.0
        with:
          card: wakatime
          options: username=${{ github.repository_owner }}&layout=compact&theme=transparent
          path: assets/wakatime.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit cards
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add profile/*.svg
          git commit -m "Update README cards" || exit 0
          git push
